packages:
  # the root package.json
  - "."
  # all packages in subdirs of packages/ and components/
  - "packages/**"
  - "docs"
  - "viteplay"
allowBuilds:
  cypress: true
  esbuild: true
  vue-demi: true
